/**
 * Api Comprathor
 * Utilizacion Api Rest
 *
 * OpenAPI spec version: V1
 * Contact: www.naxer.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Producto { 
    descripcion?: string;
    fechaCreacion?: Date;
    id?: number;
    idCategoria?: number;
    nombre?: string;
    precio?: number;
    urlImage?: string;
}
