/**
 * Api Comprathor
 * Utilizacion Api Rest
 *
 * OpenAPI spec version: V1
 * Contact: www.naxer.es
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Producto } from './producto';


export interface Puntuacion { 
    comentario?: string;
    id?: number;
    nivelCalidad?: number;
    nivelDiseno?: number;
    nivelPrecio?: number;
    producto?: Producto;
}
